
version: 2

models:
    - name: fct_sales
      description: "Sales Table"
      columns:
          - name: "ReferenceID"
            description: "The primary key for this table"
            tests:
                - not_null